### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by jacobtb23** [aws/aws-imds-packet-analyzer#3]
Hello, I have installed this solution and run the bash script to check for any missing dependencies, but I am consistently getting the error: 

"
sh-4.2$ sudo python3 imds_snoop.py
Traceback (most recent call last):
  File "imds_snoop.py", line 158, in <module>
    fileConfig('logging.conf')
  File "/usr/lib64/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib64/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib64/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
"

I have tried re-checking for any missing dependencies with no luck. Is anyone aware of a fix for this?

**Comment by geanboegman** [comment]
Pushed a change to make the `logging.conf` file optional, please let me know if this resolves your issue.

**Comment by jacobtb23** [comment]
Thank you for doing that!

**Comment by jacobtb23** [comment]
I will let you know.
