### ISSUE TITLE
Broken after Ubuntu 22.04 update to kernel 6.5.0-1014-aws

### ISSUE THREAD

**Issue by pkranjan** [aws/aws-imds-packet-analyzer#9]
```
$ uname -a
Linux ip-XX-XX-XX-XX 6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ sudo python3 src/imds_snoop.py 
Logging to /var/log/imds/imds-trace.log
/virtual/main.c:47:53: error: no member named 'iov' in 'struct iov_iter'
        const struct iovec * iov = msghdr->msg_iter.iov;
                                   ~~~~~~~~~~~~~~~~ ^
1 error generated.
Traceback (most recent call last):
  File "/home/ubuntu/aws-imds-packet-analyzer/src/imds_snoop.py", line 195, in <module>
    b = BPF('bpf.c')
  File "/usr/lib/python3/dist-packages/bcc-0.29.1+008ea09e-py3.10.egg/bcc/__init__.py", line 479, in __init__
Exception: Failed to compile BPF module b'/home/ubuntu/aws-imds-packet-analyzer/src/bpf.c'
```

**Comment by geanboegman** [comment]
Thank you for reporting this. I will investigate and revert although it might take some time, please share if you find a possible solution.

**Comment by geanboegman** [comment]
Addressed by https://github.com/aws/aws-imds-packet-analyzer/commit/a9a4b25f49c6e98b244fddd852ad60f99e74441a
